package-lock.json, packages/web/Dockerfile
=> fix: fixed package issues

packages/web/src/components/DashboardLayout/index.jsx, packages/web/src/components/DashboardLayout/mobileNav.jsx, packages/web/src/pages/api-status/api-status.jsx, packages/web/vite.config.js
Added preview config to the vite config file.
=> chore: optimized app for production

packages/web/src/components/Blogcomponents/Cards.jsx, packages/web/src/components/Blogcomponents/Cta.jsx, packages/web/src/components/Blogcomponents/Header.jsx, packages/web/src/components/Blogcomponents/Hero.jsx, packages/web/src/pages/Blog/Ai.jsx, packages/web/src/pages/Blog/Grammar.jsx, packages/web/src/pages/Blog/Jobs.jsx, packages/web/src/pages/Blog/Tips.jsx
=> Styles: feat(FRO-12-BLOG) added additional styles

packages/web/package-lock.json, packages/web/src/components/Navbar/navbar.module.css, packages/web/src/modules/static/landing-page/Charcters.jsx, packages/web/src/modules/static/landing-page/Cta.jsx, packages/web/src/modules/static/landing-page/Faq.jsx, packages/web/src/modules/static/landing-page/Footer.jsx, packages/web/src/modules/static/landing-page/Hero.jsx, packages/web/src/modules/static/landing-page/HowToUse.jsx, packages/web/src/modules/static/landing-page/NewsLetter.jsx, packages/web/src/modules/static/landing-page/Utilise.jsx, packages/web/src/modules/static/landing-page/footer.module.css, packages/web/src/modules/static/landing-page/styles/index.module.css
- Added hover state for all buttons
- Fixed overflow on hero when resized
- Changed background to white and removed box shadow from the Characters section
- Changed the shade of purple for active state and image background on for image on How To Use section
Uploading Gritty.mp4…
=> fix: update landing page

packages/api/app.js
=> update: update cors to allow all

packages/api/controller/quizController.js
=> fixed merge issues

packages/api/controller/auth/user.controller.js, packages/api/controller/forgotPasswordController.js, packages/api/routes/auth.routes.js, packages/api/services/email.service.js, packages/api/utilities/dynamicTemplates.js
This PR handles forgot password
=> feat(BE-15): endpoint for reset password

packages/api/app.js, packages/api/controller/contactUsController.js, packages/api/database/models/contactUsSchema.js, packages/api/routes/contactRoutes.js, packages/api/routes/index.route.js
- To receive user contact information/feedback.
- Store to the database. 
- Returns message received successfully.
=> feat(BAC-27): create the contact us endpoint to receive user queries.

packages/api/controller/auth/user.controller.js, packages/api/controller/forgotPasswordController.js, packages/api/services/email.service.js, packages/api/utilities/generateToken.js, packages/api/utilities/validation/auth.validation.js
The pR handles forgot password
=> Ft forgot password

packages/web/src/App.jsx, packages/web/src/modules/modal/quizpopup/QuizPopUp.jsx, packages/web/src/modules/modal/quizpopup/QuizPopUp.module.scss, packages/web/src/modules/static/quizgame/QuizGame.jsx, packages/web/src/modules/static/quizgame/QuizGame.module.scss
=> fix: css bug fix on the QuizGame page

packages/web/src/pages/Blog/Homepage.jsx, packages/web/src/pages/about/About.jsx, packages/web/src/pages/contact/Contact.module.css, packages/web/src/pages/contact/index.jsx
- Implement dark mode for newly created contact page
Linear ticket:
https://linear.app/team-grit/issue/FRO-40/create-website-dark-mode-functionality
=> (fro-40)/create dark mode functionality

packages/web/src/pages/api-status/Report/ReportDetail.jsx
http://localhost:5000/app-status
=> added api status

packages/web/src/components/Navbar/navbar.module.css, packages/web/src/index.css, packages/web/src/modules/auth/login/login.jsx, packages/web/src/modules/auth/signup/step2/step2.jsx, packages/web/src/pages/profile/profileScreen.jsx
Replace the window history when signed in and signed out.
Protected Route not added yet
Also fixed Mobile Drawer z-index
=> fix redirect on signin and signout

packages/web/src/modules/auth/login/login.jsx, packages/web/src/modules/auth/login/login.module.css, packages/web/src/modules/modal/quizpopup/QuizPopUp.jsx
the label and the input form did not have equal spacing
i was able to make the spacing equal
=> FRO2-40-login-page-form

packages/web/src/pages/Legal/index.jsx
I was asked to use the corresponding light purple to replace the light blue on the legal page and to also change the text color to the style guide black, and the heading font to the heading fonts on other pages.
=> Improvement: Made changes to legal page

packages/web/src/lib/constants/index.js
Reverts workshopapps/grammarcheckerai.web#318
=> Revert "chore- update base Api URL"

packages/web/src/modules/auth/login/login.jsx, packages/web/src/modules/auth/login/login.module.css
=> chore: aligned checkbox with text

packages/web/src/components/Blogcomponents/Cta.jsx, packages/web/src/pages/Blog/Ai.jsx, packages/web/src/pages/Blog/Grammar.jsx, packages/web/src/pages/Blog/Jobs.jsx, packages/web/src/pages/Blog/Tips.jsx
=> feat/fRO2-117-BlogPage: Added redirect links to the sub pages.

packages/api/routes/paystackRouter.js
Fixed Paystack bug on creating subscription on database
=> Fixed Paystack bug on creating subscription

README.md, packages/web/README.md, packages/web/index.html, packages/web/src/components/Careers/footer.jsx, packages/web/src/components/Faq/faq_footer.jsx, packages/web/src/modules/auth/signup/step1/step1.jsx, packages/web/src/modules/auth/signup/step2/step2.jsx, packages/web/src/modules/setting/home-settings/help-support/help-support.jsx, packages/web/src/modules/static/emailtemplate/EmailTemplate.jsx, packages/web/src/modules/static/emailtemplate/newsletterTemplate.jsx, packages/web/src/modules/static/emailtemplate/signInTemplate.jsx, packages/web/src/modules/static/landing-page/Footer.jsx, packages/web/src/modules/static/newsletter/NewsletterPage.jsx, packages/web/src/modules/static/testimonials/Ratings.jsx, packages/web/src/modules/static/testimonials/Testimonial.jsx, packages/web/src/modules/transcribe/index.jsx, packages/web/src/pages/Blog/Grammar.jsx, packages/web/src/pages/Blog/Tips.jsx, packages/web/src/pages/about/About.jsx, packages/web/src/pages/api-status/api-status.jsx, packages/web/src/pages/career/Application.jsx, packages/web/src/pages/career/Career.jsx, packages/web/src/pages/career/Roles.jsx, packages/web/src/pages/profile/ConfirmDeleteAccount.jsx, packages/web/src/pages/profile/DeleteAccount.jsx
=> feat/FRO2-133-Conflicting-Name: Changed brand name from grittygrammar to Speak Better

packages/api/app.js, packages/api/config/environment.js, packages/api/controller/crons.js, packages/api/controller/newsLetterSubscriptionController.js, packages/api/database/models/newsLetterSubscriptionSchema.js, packages/api/package.json, packages/api/routes/index.route.js, packages/api/routes/newsLetterSubscriptionRoute.js
[Linear Ticket:BAC2-25](https://linear.app/team-grit/issue/BAC2-25/newsletter-subscription)
- Create an endpoint (**Newsletter Subscription**) that sends newsletters to subscribers which can be from the user collections(registered users) and the new subscribers. 
- I also did a minor refactoring: I updated the environment variable and added **NEWSLETTER_TEMPLATE_ID.**
- I added a 404 error endpoint.
=> feat/BAC2-25: Create a newsletter Endpoint using cronjob, modify the code-base and added a 404 error message endpoint

packages/api/controller/payController.js, packages/api/routes/paystackRouter.js
Bug Fix: Passing data to query
Error checks and treatment
=> Bug Fix: Passing data to query

packages/api/app.js, packages/api/controller/crons.js
=> Removed cron job

packages/api/controller/payController.js
Linear task links 👍 :
verify payment made by user "https://linear.app/team-grit/issue/BAC2-64/premium-subscription-for-users"
created a verify endpoint that takes in the payment reference
verify that the transaction is successful
updates the database to change status of transaction
=> chore:fixed bug on subscription

packages/api/controller/auth/authThirdPartyController.js, packages/api/routes/auth.routes.js
=> FEAT/BAC2-20/fb-auth/Social Login

packages/api/controller/quickTranscribeControllers.js
Include the `transcription` in the /quickTranscribe endpoint return value
=> Feat/bac2 68/quick transcribe

packages/api/controller/payController.js, packages/api/routes/payRoute.js, packages/api/routes/paystackRouter.js
Fixed cors error on redirect
Fixed merge errors
=> Fixed bug on cancel subscription

packages/web/src/modules/account/conversation/index.jsx
=> feat/FRO2-45-ConversationPage: Fixed the bot on the conversation page

packages/api/controller/payController.js, packages/api/database/models/subscriptionSchema.js
Added unique feature to subscription email
=> Added unique feature to subscription email

packages/web/src/modules/account/conversation/index.jsx
Fixed error when showing the premium popup when a user does not have a subscription.
=> fix: error on audio length

packages/api/controller/auth/authThirdPartyController.js
=> callback changes

packages/web/src/hooks/auth/useAuthLinkedIn.jsx, packages/web/src/hooks/auth/useGetLinkedInLink.jsx, packages/web/src/lib/constants/index.js, packages/web/src/modules/auth/login/login.jsx
=> Made latest changes

packages/api/Tests/test.json
[Linear Ticket ](https://linear.app/team-grit/issue/BAC2-66/swagger-documentation-api-documentation#comment-5c35cb88)
- Test for all APIs Endpoints on the speak better web.
=> feat/BAC2-66: Swagger API documentation for endpoints present in the app

packages/api/database/models/contactUsSchema.js
Remove the unique option from the email property.
=> contact-us endpoint email validation fixed

packages/web/src/modules/account/conversation/converse.jsx
=> Fixed error message

packages/web/package-lock.json, packages/web/package.json, packages/web/src/modules/auth/signup/step2/schema/index.js, packages/web/src/modules/auth/signup/step2/step2.jsx, packages/web/src/modules/auth/signup/step2/step2.module.css
- Added proper error messages to indicate what is wrong to user.
- Error messages only comes up when user clicks out of input field or tries to submit invalid or empty form
https://user-images.githubusercontent.com/72361299/206283113-4aa780ad-6bdc-4329-b73d-0bc4cd8970ef.mp4
=> fix: add proper form validations for sign up page

packages/web/src/modules/auth/login/login.jsx, packages/web/src/modules/auth/signup/step2/step2.jsx, packages/web/src/modules/static/testimonials/Testimonial.jsx
Sign Up Fix
removed the 404 failed error for the google authentication.
removed the 500 error all social media authentication had on click
=> Fix-Feat/Sign-up-fix

packages/web/src/components/Careers/culture.jsx, packages/web/src/modules/account/conversation/converse.jsx, packages/web/src/pages/career/Career.jsx
@bohemiancode-x Fixed the page overflow
Ticket - https://linear.app/team-grit/issue/FRO2-190/career-and-culture
=> FRO2-190: BUG FIX - CAREER AND CULTURE

packages/api/app.js
=> Conversation optimization

packages/web/src/modules/static/newsletter/NewsletterPage.jsx
@bohemiancode-x Fixed 
Ticket - https://linear.app/team-grit/issue/FRO2-173/newsletter
=> FRO2-173: BUG FIX - INCREASE BUTTON SIZE

packages/web/src/modules/static/landing-page/Footer.jsx, packages/web/src/modules/static/landing-page/footer.module.css
@bohemiancode-x @shalomtaiwo Done
Ticket - https://linear.app/team-grit/issue/FRO2-189/footer
=> FRO2-189: BUG FIX - FOOTER OVERLAP

packages/web/src/modules/static/landing-page/Hero.jsx, packages/web/src/modules/static/landing-page/Utilise.jsx
- Fixed contrast text color on hero
=> fix: change text color on hero and make robot not cover text

packages/api/controller/newsLetterSubscriptionController.js
- I update the Action URL with the FE route.
=> added the FE route to action URL

packages/web/src/pages/contact/Contact.module.css
=> chore: removed outline from contact page

packages/web/src/components/Navbar/index.jsx, packages/web/src/modules/auth/signup/step2/step2.jsx, packages/web/src/modules/premium/popup/checkout.jsx
Fix Signup redirection when logged in
=> fix-auth redirection when logged in

packages/web/src/App.jsx, packages/web/src/components/Navbar/index.jsx
Added premium link to the navbar
=> chore: added premium to navbar

packages/api/Tests/test.json
- Swagger Documentation  for the speak better APIs
=> Swagger Documentation for the Speak Better APIs

packages/web/src/pages/Blog/Ai.jsx
=> chore: fixed image issue

packages/web/src/modules/static/landing-page/Hero.jsx
fixed the width of text in hero section to initial state
after
=> fixed hero text width

packages/api/app.js, packages/api/controller/axios.js, packages/api/controller/contactUsController.js, packages/api/controller/logoutcontroller.js, packages/api/controller/stripeController.js, packages/api/controller/testController.js, packages/api/database/models/subscriptionSchema.js
=> Bug fix on Stripe Premium

packages/api/controller/payController.js, packages/api/controller/stripeController.js, packages/api/controller/subscriptionController.js, packages/api/database/models/subscriptionSchema.js, packages/api/routes/index.route.js, packages/api/routes/payRoute.js, packages/api/routes/stripeRoutes.js, packages/api/routes/subscriptionRouter.js, packages/api/server.js
Added Stripe Cancel
Added Stripe Verify 
Added Endpoint for Getting all subscriptions
=> Added Stripe cancel

packages/web/src/modules/account/history/correction.jsx, packages/web/src/modules/account/history/history.jsx, packages/web/src/modules/account/history/modal.jsx
Updated with new chat history endpoint
=> fix: update chat history with new endpoint

packages/api/controller/newsLetterSubscriptionController.js
=> modify newsletters subscriber

packages/web/src/pages/about/data/data.js, packages/web/vite.config.js
=> team behind product adjustments
